# permissions for end users to edit sharedvolumesinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharedvolumesinfo-editor-role
rules:
- apiGroups:
  - internal.storageos.com
  resources:
  - sharedvolumesinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - internal.storageos.com
  resources:
  - sharedvolumesinfoes/status
  verbs:
  - get
