name: Test and build image

on: [push, pull_request]

env:
  IMG: storageos/api-manager:develop

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: go-test
        run: make test

  build-image:
    needs: test
    runs-on: ubuntu-latest
    name: Build container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        run: make docker-build
      - name: Login to container registry
        if: github.ref == 'ref/heads/master'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push container image
        if: github.ref == 'ref/heads/master'
        run: make docker-push
