name: Test and build image

on: [push, pull_request]

env:
  IMG: storageos/api-manager:develop

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.2.0
        with:
          args: --timeout=5m

  test-build:
    name: Run tests and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: go-test
        run: make test
      - name: build
        run: make manager

  build-image:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        run: make docker-build
